### ISSUE TITLE
pawn promotion seems incorrect

### ISSUE THREAD

**Issue by mikeblas** [Darokahn/Chess#2]
The pawn promotion code looks for "wd" and "bd" pieces. No piece is named "d".

The search should probably be for "wp" and "bp" pieces.

**Comment by Darokahn** [comment]
I made two seperate pieces for a pawn that has moved and a pawn that hasn't, since their rules are slightly different. After a pawn moves, it is changed to "wd" or "bd", "d" standing for demoted. "demoted" made sense to me since they can no longer jump two spaces forward.
